# Generated by Django 4.0 on 2024-02-06 15:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('km', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('presentación', models.CharField(max_length=255)),
                ('pesounidad', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('km', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transporte.ciudad')),
            ],
        ),
        migrations.CreateModel(
            name='Tipodocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=255)),
                ('marca', models.CharField(max_length=255)),
                ('modelo', models.CharField(max_length=255)),
                ('year', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(limit_value=9999)])),
                ('fechavencisoat', models.DateField()),
                ('fechavencitecno', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='licencia',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='documento',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.CreateModel(
            name='Rutamaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Unidades', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(limit_value=9999)])),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transporte.material')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transporte.ruta')),
            ],
        ),
        migrations.AddField(
            model_name='ruta',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transporte.customuser'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='tipodocumento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transporte.tipodocumento'),
        ),
    ]
