# Generated by Django 4.0 on 2024-02-06 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0002_ciudad_material_ruta_tipodocumento_vehiculo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='telefono',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
