# Generated by Django 4.0 on 2024-02-06 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0004_alter_customuser_telefono'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='presentación',
            new_name='presentacion',
        ),
    ]
