# Generated by Django 4.0 on 2024-02-07 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0005_rename_presentación_material_presentacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruta',
            name='vehiculo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='transporte.vehiculo'),
        ),
    ]
