# Generated by Django 4.0 on 2024-02-08 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0007_ruta_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruta',
            name='valortotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=22),
        ),
    ]
