# Generated by Django 4.0 on 2024-02-08 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0008_ruta_valortotal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruta',
            name='valortotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=22, null=True),
        ),
    ]
