# Generated by Django 4.0 on 2024-02-10 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0011_vehiculo_swative'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruta',
            name='SwAtive',
            field=models.IntegerField(default=1),
        ),
    ]
